# Set platform to iOS 15.0 to satisfy Firebase and modern plugin requirements
platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronous so they can be aggregated.
# For more information, see https://guides.cocoapods.org/using/analytics.html
install! 'cocoapods', :deterministic_uuids => false

# Load the generated pod helper which contains common Flutter logic
# This file is created automatically during 'flutter pub get' or 'flutter build ios'
generated_pod_helper_path = File.join(File.dirname(__FILE__), 'Flutter', 'generated_pod_helper.rb')
if File.exist?(generated_pod_helper_path)
  load generated_pod_helper_path
else
  # On CI, flutter pub get might not have created this yet if called from pod install directly.
  # However, flutter build ios should have created it.
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # flutter_install_all_ios_pods is defined in generated_pod_helper.rb
  if defined?(flutter_install_all_ios_pods)
    flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # flutter_additional_ios_build_settings is also in generated_pod_helper.rb
    if defined?(flutter_additional_ios_build_settings)
      flutter_additional_ios_build_settings(target)
    end
    
    # Force all targets to iOS 15.0 to suppress deployment target warnings and fix Xcode 16 build errors
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
