default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # 1. Update version if needed
    # increment_build_number(xcodeproj: "Runner.xcodeproj")
    
    # 2. Build the app (ipa)
    build_app(
      scheme: "Runner",
      workspace: "Runner.xcworkspace",
      include_bitcode: false
    )
    
    # 3. Upload to TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
